apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name }}-service
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 80
  selector:
    app: {{ .Values.frontend.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.name }}-service
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: 5000
  selector:
    app: {{ .Values.backend.name }}